Repository haysberg/azurwiki, pull requests merged in 2023-08, with the labels that each got.

#80 Ajout d'une page pour payer moins cher
  docs/01-accueil.md
  docs/04-tips.md
  docusaurus.config.js
Labels: Idée, Non-technique

#81 Ajouter mon contact
  docs/02-anciens.md
Labels: Non-technique

#84 docs: add geogramint to osint tools
  docs/10-osint/index.md
Labels: Idée

#85 Ajout de la fonction de recherche
  docusaurus.config.js
  package-lock.json
  package.json
Labels: Important

#86 Ajout de mon contact
  docs/02-anciens.md
Labels: Non-technique
